name = "Freelance"
license = "MIT"
licenselink = "https://github.com/filipeamoreira/hugo-freelance/blob/master/LICENSE.md"
description = "Easily create beautifully simple personal freelance websites"
homepage = "https://github.com/filipeamoreira/hugo-academic"
min_version = 0.18
tags = ["academic",
        "portfolio",
        "responsive",
        "student",
        "personal",
        "university",
        "blog",
        "minimal",
        "freelance"
        ]
features = ["academic profile",
            "research publication system",
            "projects",
            "blog",
            "teaching",
            "contact",
            "freelance portfolio",
            ]

[author]
  name = "Filipe A Moreira"
  homepage = "https://filipeamoreira.com"

# If porting an existing theme
[original]
  name = "George Cushen"
  homepage = "https://georgecushen.com"
  repo = "https://github.com/gcushen/hugo-academic"
